---
project:
    name: ''
    sample_list: 'sample.list'
    pair_table: 'pair.table'
    bam_table: 'bam.table'
reference:
    fasta: '/home/bwubb/resources/Genomes/Human/GRCh37/human_g1k_v37.fasta.gz'
    key: 'GRCh37'
    gc_wiggle: '/home/bwubb/resources/Genomes/Human/GRCh37/human_g1k_v37.gc50Base.wig.gz'
resources:
    targets_key: ''
    targets_bed: ''
    targets_bedgz: ''
    targets_intervals: ''
    splice_snv: '/home/bwubb/.vep/spliceai/spliceai_scores.raw.snv.hg19.vcf.gz'
    splice_indel: '/home/bwubb/.vep/spliceai/spliceai_scores.raw.indel.hg19.vcf.gz'
    gnomAD: '/home/bwubb/.vep/gnomAD/gnomad.v3.1.1.hg19.exomes.gz'
    clinvar: '/home/bwubb/.vep/clinvar/vcf_GRCh37/clinvar.vcf.gz'
    revel: '/home/bwubb/.vep/revel/revel_grch37.tsv.gz'
    utrannotator: '/home/bwubb/.vep/Plugins/UTRannotator/uORF_5UTR_GRCh37_PUBLIC.txt'
