---
project:
    name: ''
    sample_list: 'sample.list'
    pair_table: 'pair.table'
    bam_table: 'bam.table'
    normal_list: 'normal.list'
    tumor_list: 'tumor.list'
reference:
    fasta: '$HOME/resources/Genomes/Human/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.fa'
    key: 'GRCh38'
    gc_wiggle: '$HOME/resources/Genomes/Human/GRCh38/Homo_sapiens.GRCh38.dna.primary_assembly.gc50Base.wig.gz'
resources:
    targets_key: ''
    targets_bed: ''
    targets_bedgz: ''
    targets_intervals: ''
    splice_snv: '$HOME/.vep/spliceai/spliceai_scores.raw.snv.hg38.vcf.gz'
    splice_indel: '$HOME/.vep/spliceai/spliceai_scores.raw.indel.hg38.vcf.gz'
    gnomAD: '$HOME/.vep/gnomAD/gnomad.v3.1.1.hg38.genomes.gz'
    clinvar: '$HOME/.vep/clinvar/vcf_GRCh38/clinvar.vcf.gz'
    revel: '$HOME/.vep/revel/revel_grch38.tsv.gz'
    utrannotator: '$HOME/.vep/Plugins/UTRannotator/uORF_5UTR_GRCh38_PUBLIC.txt'
    loftee: '$HOME/.vep/Plugins/loftee'
analysis:
    purity_table: 'purity.table'
    vlr: 'default_somatic.yml'
